---
Name: silverware-blog
---

# Configure Content Controller:

SilverStripe\CMS\Controllers\ContentController:
  required_js:
    - "silverware/blog: client/dist/js/bundle.js"
  required_css:
    - "silverware/blog: client/dist/styles/bundle.css"

# Configure Member Extensions:

SilverStripe\Security\Member:
  extensions:
    - SilverWare\Blog\Extensions\MemberExtension
    - SilverWare\Extensions\Model\URLSegmentExtension
